name: Smoke Tests

on: push

jobs:
  Only-AddToCart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart
          
      - name: Upload Cypress Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
            name: Mochawesome Test Report
            path: cypress/reports/mochawesome.html # adjust path if needed
        
      - name: Post Cypress Report Link
        run: |
          echo "### 📋 [View Test Report Artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
        