name: Parallel Tests (addToCart & registerFlow)

on: push

jobs:
  AddToCart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart-GitHubActions

      - name: Upload Cypress Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome Test Report - Add To Cart
          path: cypress/reports/

  RegisterFlow-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registrationFlow-GitHubActions

      - name: Upload Cypress Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome Test Report - RegisterFlow
          path: cypress/reports/